default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pgloader
  password: password
  host: localhost

development:
  <<: *default
  database: dv_dev

test:
  <<: *default
  database: dv4_development_test

production:
  <<: *default
  database: divan
  schema_search_path: "divan, public"
  username: pgloader
  password: 123456aA
  host: 172.16.23.104
