class AddIndexesToTables < ActiveRecord::Migration[7.0]
   def change
#     add_index :access_controls, :user_id
#     add_index :access_controls, :role_id
#     add_index :access_groupings, :access_group_id
#     add_index :access_groupings, :article_id
#     add_index :access_groupings, :user_id
#     add_index :access_groups, :user_id
#     add_index :areaings, :article_area_id
#     add_index :areaings, :article_id
#     add_index :areaing_histories, :article_id
#     add_index :areaing_histories, :article_area_id
#     add_index :areaing_histories, :user_id
#     add_index :areaing_histories, :workflow_transition_id
#     add_index :areaing_histories, :areaing_id
#     add_index :articles, :slug
#     add_index :articles, :workflow_state_id
#     add_index :articles, :content_template_id
#     add_index :articles, :access_group_id
#     add_index :articles, :user_id
#     add_index :articles, :external_id
#     add_index :articles, :publish_source_id
#     add_index :article_areas, :user_id
#     add_index :article_events, :user_id
#     add_index :article_formats, :user_id
#     add_index :article_histories, :user_id
#     add_index :article_histories, :article_id
#     add_index :article_histories, :workflow_transition_id
#     add_index :article_relation_types, :user_id
#     add_index :article_relation_types, :reverse_relation_id
#     add_index :article_sources, :user_id
#     add_index :article_types, :user_id
#     add_index :assignments, :user_id
#     add_index :assignments, :role_id
#     add_index :assignments, :assigner_id
#     add_index :carriers, :source_workflow_state_id
#     add_index :carriers, :target_workflow_state_id
#     add_index :carriers, :user_id
#     add_index :comments, :commentable_id
#     add_index :comments, :user_id
#     add_index :content_templates, :user_id
#     add_index :contributions, :article_id
#     add_index :contributions, :role_id
#     add_index :contributions, :duty_id
#     add_index :contributions, :profile_id
#     add_index :contribution_histories, :article_id
#     add_index :contribution_histories, :role_id
#     add_index :contribution_histories, :duty_id
#     add_index :contribution_histories, :profile_id
#     add_index :contribution_histories, :user_id
#     add_index :contribution_histories, :workflow_transition_id
#     add_index :contribution_histories, :contribution_id
#     add_index :datings, :article_event_id
#     add_index :datings, :article_id
#     add_index :dating_histories, :article_id
#     add_index :dating_histories, :article_event_id
#     add_index :dating_histories, :user_id
#     add_index :dating_histories, :workflow_transition_id
#     add_index :dating_histories, :dating_id
#     add_index :duties, :user_id
#     add_index :formatings, :article_format_id
#     add_index :formatings, :article_id
#     add_index :formating_histories, :article_format_id
#     add_index :formating_histories, :article_id
#     add_index :formating_histories, :user_id
#     add_index :formating_histories, :workflow_state_id
#     add_index :formating_histories, :formating_id
#     add_index :formating_histories, :workflow_transition_id
#     add_index :home_settings, :user_id
#     add_index :interconnects, :user_id
#     add_index :involvements, :article_id
#     add_index :involvements, :publisher_id
#     add_index :keywords, :user_id
#     add_index :kinships, :user_id
#     add_index :kinships, :kin_id
#     add_index :kinships, :article_relation_type_id
#     add_index :kinships, :article_id
#     add_index :kinship_histories, :user_id
#     add_index :kinship_histories, :kin_id
#     add_index :kinship_histories, :article_id
#     add_index :kinship_histories, :article_relation_type_id
#     add_index :kinship_histories, :workflow_transition_id
#     add_index :kinship_histories, :kinship_id
#     add_index :languages, :user_id
#     add_index :locations, :user_id
#     add_index :messages, :sender_id
#     add_index :messages, :parent_id
#     add_index :messagings, :recipient_id
#     add_index :messagings, :message_id
#     add_index :mirorrs, :user_id
#     add_index :note_templates, :user_id
#     add_index :notifications, :notifiable_id
#     add_index :notifications, :user_id
#     add_index :notifications, :emmiter_id
#     add_index :notification_settings, :user_id
#     add_index :notings, :note_template_id
#     add_index :notings, :article_id
#     add_index :notings, :user_id
#     add_index :originatings, :article_id
#     add_index :originatings, :article_source_id
#     add_index :originating_histories, :article_id
#     add_index :originating_histories, :article_source_id
#     add_index :originating_histories, :originating_id
#     add_index :originating_histories, :user_id
#     add_index :originating_histories, :workflow_transition_id
#     add_index :profiles, :user_id
#     add_index :profiles, :email
#     add_index :profiles, :dabir_personnel_id
#     add_index :profiles, :dabir_department_id
#     add_index :profile_groupings, :profile_id
#     add_index :profile_groupings, :profile_group_id
#     add_index :profile_groupings, :user_id
#     add_index :profile_groups, :user_id
#     add_index :profile_groups, :workflow_id
#     add_index :publications, :article_id
#     add_index :publications, :publisher_id
#     add_index :publications, :location_id
#     add_index :publications, :publish_source_id
#     add_index :publishers, :user_id
#     add_index :publish_sources, :publisher_id
#     add_index :publish_sources, :user_id
#     add_index :roles, :user_id
#     add_index :role_accesses, :role_id
#     add_index :role_accesses, :access_group_id
#     add_index :sectionings, :section_id
#     add_index :sectionings, :section_item_id
#     add_index :sections, :workflow_id
#     add_index :sections, :user_id
#     add_index :section_items, :section_id
#     add_index :section_items, :user_id
#     add_index :speakings, :language_id
#     add_index :speakings, :article_id
#     add_index :speaking_histories, :article_id
#     add_index :speaking_histories, :language_id
#     add_index :speaking_histories, :user_id
#     add_index :speaking_histories, :workflow_transition_id
#     add_index :speaking_histories, :speaking_id
#     add_index :state_pages, :workflow_state_id
#     add_index :taggings, :taggable_id
#     add_index :taggings, :target_id
#     add_index :tagging_histories, :taggable_id
#     add_index :tagging_histories, :target_id
#     add_index :tagging_histories, :user_id
#     add_index :tagging_histories, :article_id
#     add_index :tagging_histories, :workflow_transition_id
#     add_index :tagging_histories, :tagging_id
#     add_index :title_types, :user_id
#     add_index :titlings, :title_type_id
#     add_index :titlings, :article_id
#     add_index :typings, :article_type_id
#     add_index :typings, :article_id
#     add_index :typing_histories, :article_type_id
#     add_index :typing_histories, :article_id
#     add_index :typing_histories, :typing_id
#     add_index :typing_histories, :user_id
#     add_index :typing_histories, :workflow_transition_id
#     add_index :uploads, :uploadable_id
#     add_index :uploads, :user_id
#     add_index :upload_histories, :uploadable_id
#     add_index :upload_histories, :user_id
#     add_index :upload_histories, :workflow_transition_id
#     add_index :upload_histories, :speaking_id
#     add_index :upload_histories, :upload_id
#     add_index :users, :email
#     add_index :users, :current_role_id
#     add_index :votes, :user_id
#     add_index :votes, :voting_id
#     add_index :votes, :article_id
#     add_index :votings, :votable_id
#     add_index :word_templates, :workflow_id
#     add_index :word_templates, :user_id
#     add_index :workflows, :user_id
#     add_index :workflows, :start_node_id
#     add_index :workflows, :admin_id
#     add_index :workflows, :moderator_id
#     add_index :workflow_role_accesses, :workflow_id
#     add_index :workflow_role_accesses, :role_id
#     add_index :workflow_states, :workflow_id
#     add_index :workflow_states, :node_id
#     add_index :workflow_states, :role_id
#     add_index :workflow_transitions, :workflow_id
#     add_index :workflow_transitions, :from_state_id
#     add_index :workflow_transitions, :to_state_id
#     add_index :workflow_transitions, :user_id
#     add_index :workflow_transitions, :role_id
#     add_index :workflow_transitions, :article_id
   end
end
